__all__ = ["ModelCfg"]

ModelCfg = {
    'mixer': {
            'cifar10' :{'S':{'dim':64,
                            'token_dim':128,
                            'channel_dim':128,
                            'num_layers':4,
                            'num_class':10,
                            'image_size':32,
                            'patch_size':4},
                            
                            'B':{'dim':64,
                            'token_dim':256,
                            'channel_dim':256,
                            'num_layers':4,
                            'num_class':10,
                            'image_size':32,
                            'patch_size':4},
                            
                            'L':{'dim':128,
                            'token_dim':256,
                            'channel_dim':256,
                            'num_layers':8,
                            'num_class':10,
                            'image_size':32,
                            'patch_size':4},},
        
                'cifar100':{'S':{'dim':64,
                            'token_dim':128,
                            'channel_dim':128,
                            'num_layers':4,
                            'num_class':100,
                            'image_size':32,
                            'patch_size':4},
                            
                            'B':{'dim':64,
                            'token_dim':256,
                            'channel_dim':256,
                            'num_layers':4,
                            'num_class':100,
                            'image_size':32,
                            'patch_size':4},
                            
                            'L':{'dim':128,
                            'token_dim':256,
                            'channel_dim':256,
                            'num_layers':8,
                            'num_class':100,
                            'image_size':32,
                            'patch_size':4}},
                
                'TinyImageNet':{'S':{'dim':128,
                            'token_dim':256,
                            'channel_dim':256,
                            'num_layers':4,
                            'num_class':200,
                            'image_size':64,
                            'patch_size':8},
                            
                            'B':{'dim':256,
                            'token_dim':256,
                            'channel_dim':256,
                            'num_layers':6,
                            'num_class':200,
                            'image_size':64,
                            'patch_size':8},
                            
                            'L':{'dim':256,
                            'token_dim':512,
                            'channel_dim':512,
                            'num_layers':8,
                            'num_class':200,
                            'image_size':64,
                            'patch_size':8}},
                
                'STL10':  {'S':{'dim':128,
                            'token_dim':128,
                            'channel_dim':512,
                            'num_layers':4,
                            'num_class':10,
                            'image_size':96,
                            'patch_size':12},
                            
                            'B':{'dim':256,
                            'token_dim':128,
                            'channel_dim':512,
                            'num_layers':6,
                            'num_class':10,
                            'image_size':96,
                            'patch_size':12},
                            
                            'L':{'dim':256,
                            'token_dim':128,
                            'channel_dim':768,
                            'num_layers':8,
                            'num_class':10,
                            'image_size':96,
                            'patch_size':12},
                },
                
                'Celeba':  {'S':{'dim':256,
                            'token_dim':256,
                            'channel_dim':512,
                            'num_layers':4,
                            'num_class':2,
                            'image_size':224,
                            'patch_size':16},
                            
                            'B':{'dim':256,
                            'token_dim':256,
                            'channel_dim':512,
                            'num_layers':6,
                            'num_class':2,
                            'image_size':224,
                            'patch_size':16},
                            
                            'L':{'dim':512,
                            'token_dim':256,
                            'channel_dim':768,
                            'num_layers':8,
                            'num_class':2,
                            'image_size':224,
                            'patch_size':16}},
        },

    'vit':{
            'cifar10' :{'S':{'image_size':32,
                            'num_class':10,
                            'patch_size':4,
                            'hidden_dim':128,
                            'dim':64,
                            'num_heads':4,
                            'num_layers':4},
                        'B':{'image_size':32,
                            'num_class':10,
                            'patch_size':4,
                            'hidden_dim':256,
                            'dim':128,
                            'num_heads':4,
                            'num_layers':4},
                        'L':{'image_size':32,
                            'num_class':10,
                            'patch_size':4,
                            'hidden_dim':256,
                            'dim':128,
                            'num_heads':4,
                            'num_layers':6}},
            'cifar100' :{'S':{'image_size':32,
                            'num_class':100,
                            'patch_size':4,
                            'hidden_dim':256,
                            'dim':128,
                            'num_heads':4,
                            'num_layers':2},
                        'B':{'image_size':32,
                            'num_class':100,
                            'patch_size':4,
                            'hidden_dim':256,
                            'dim':128,
                            'num_heads':4,
                            'num_layers':2},
                        'L':{'image_size':32,
                            'num_class':100,
                            'patch_size':4,
                            'hidden_dim':256,
                            'dim':128,
                            'num_heads':4,
                            'num_layers':2}},
            'TinyImageNet' :{'S':{'image_size':64,
                            'num_class':200,
                            'patch_size':8,
                            'hidden_dim':256,
                            'dim':128,
                            'num_heads':4,
                            'num_layers':2},
                        'B':{'image_size':64,
                            'num_class':200,
                            'patch_size':8,
                            'hidden_dim':256,
                            'dim':128,
                            'num_heads':4,
                            'num_layers':4},
                        'L':{'image_size':64,
                            'num_class':200,
                            'patch_size':8,
                            'hidden_dim':256,
                            'dim':256,
                            'num_heads':8,
                            'num_layers':6}}
            
    },
    'TwoCNN': {
            'cifar10'  :{
                         'S':{'num_class':10},
                         'B':{'num_class':10},
                         'L':{'num_class':10}
                         },
            'cifar100' :{
                         'S':{'num_class':100},
                         'B':{'num_class':100},
                         'L':{'num_class':100}
                         },
    }
            
}